### ISSUE TITLE
X and Y is switched QRCODES DONT WORK

### ISSUE THREAD

**Issue by jpike88** [papnkukn/qrcode-svg#1]
Why on earth would you switch the x and y coordinates? Do you even test your code?

**Comment by qalqi** [comment]
Change Lines 307 and 308
       var py = (x * xsize + options.padding * xsize).toString();
        var px = (y * ysize + options.padding * ysize).toString();

**Comment by papnkukn** [comment]
A fix in v1.1.0
```js
new QRCode({
  ...
  swap: true //Swap X and Y modules
})
```
